cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.index, name='index'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    
    path('^event/new/$', views.event, name='event_new'),
	path('event/info/<str:pk>/', views.info_event, name='event_info'),
    path('event/info/<str:event_id>/edit', views.event, name='event_edit'),
    path('event/info/<str:pk>/delete/', views.delete_event, name="event_delete"),
    path('event/info/<str:pk>/confirmation/', views.confirmation_event, name="event_confirmation"),
    path('event/info/<str:pk>/denial/', views.deny_event, name="event_denial"),

    path('register/', views.register, name="register"),
    path('login/',views.loginPage, name="login"),
    path('logout /',views.logoutUser, name="logout"),
]

djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
]

cal/models.py
from email.policy import default
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Reason(models.Model):
    reason = models.TextField()

class Event(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    pending = models.IntegerField(default=0)
    adm = models.CharField(max_length=200, default='')
    reason = models.TextField(default='')

    

    MEIA = 30
    UMA = 60
    UMA_MEIA = 90
    DUAS = 120

    DURATION = (
    (MEIA, '30 min'),
    (UMA, '1h'),
    (UMA_MEIA, '1h30min'),
    (DUAS, '2h')
  )

    duration = models.IntegerField(default=0, choices=DURATION)

    @property
    def get_confirmation(self):

        if self.pending == 0:
            return f'<span style="color: #C8BA08"> Pendente </span>'
        elif self.pending == 1:
            return f'<span style="color: lime"> Confirmado </span><span>({self.adm})</span>'
        elif self.pending == 2:
            return f'<span style="color: red"> Negado </span><span>({self.adm})</span>'

    @property
    def get_html_url(self):
        url = reverse('cal:event_info', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'
    
    @property
    def get_html_time(self):
        duracao = self.duration / 60
        hora = self.start_time.hour
        minuto = self.start_time.minute
        min_format = 0

        def zero(x):
            if(len(str(x))) == 1:
                x = f'0{x}'
            else:
                x = f'{x}'
            return x

        if duracao == 0.5:
            duracao_min = 30

            if(minuto + duracao_min >=60):
                duracao_min = duracao_min - 60
                min_format = minuto + duracao_min
                min_format = zero(min_format)

                if(len(str(minuto))) == 1:
                    return f'<p> {hora}h0{minuto} - {hora + 1}h{min_format}<p>'
                else:
                    return f'<p> {hora}h{minuto} - {hora + 1}h{min_format}<p>'
            else:
                min_format = minuto + duracao_min
                min_format = zero(min_format)

                if(len(str(minuto))) == 1: 
                    return f'<p> {hora}h0{minuto} - {hora}h{min_format}<p>'
                else:
                    return f'<p> {hora}h{minuto} - {hora}h{min_format}<p>'
                    

        elif duracao == 1:
            duracao = int(duracao)
            return f'<p> {hora}h{minuto} - {hora + duracao}h{minuto}<p>'

        elif duracao == 1.5:
            duracao_min = 30

            if(minuto + duracao_min >=60):
                duracao_min = duracao_min - 60
                min_format = minuto + duracao_min
                min_format = zero(min_format)

                if(len(str(minuto))) == 1:
                    return f'<p> {hora}h0{minuto} - {hora + 2}h{min_format}<p>'
                else:
                    return f'<p> {hora}h{minuto} - {hora + 2}h{min_format}<p>'
            else:
                min_format = minuto + duracao_min
                min_format = zero(min_format)

                if(len(str(minuto))) == 1:      
                    return f'<p> {hora}h0{minuto} - {hora + 1}h{min_format}<p>'
                else:
                    return f'<p> {hora}h{minuto} - {hora + 1}h{min_format}<p>'

        elif duracao == 2:
            duracao = int(duracao)
            return f'<p> {hora}h{minuto} - {hora + duracao}h{minuto}<p>'
        
            
    @property
    def get_hour(self):
        return self.start_time.hour

cal/forms.py
from csv import field_size_limit
from django.forms import ModelForm, DateInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from cal.models import Event, Reason

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      # 'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = ['title', 'description', 'start_time', 'duration']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    # self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class CreateFormUser(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']
  
class ReasonForm(ModelForm):
  class Meta:
    model = Reason
    fields = '__all__'

cal/views.py
from datetime import datetime, timedelta, date
from multiprocessing import context
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from .models import Event
from .forms import CreateFormUser, ReasonForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import *
from .utils import Calendar
from .forms import EventForm

def index(request):
    return render(request, 'cal/index.html')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

@login_required(login_url='cal:login')
def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        obj = form.save(commit=False) # Return an object without saving to the DB
        obj.host = request.user # Add an author field which will contain current user's id
        obj.save() # Save the final "real form" to the DB
        return HttpResponseRedirect(reverse('cal:calendar'))

    return render(request, 'cal/event.html', {'form': form})

@login_required(login_url='cal:login')
def info_event(request, pk):
    evento = Event.objects.get(id=pk)
    
    if evento.pending == 0:
        evento.adm = str(request.user)
        evento.save()

    context = {'evento': evento}
    return render(request, 'cal/info.html', context)
    
@login_required(login_url='cal:login')
def delete_event(request, pk):
    evento = Event.objects.get(id=pk)
    context = {'evento': evento}

    if request.user != evento.host and not request.user.is_superuser:
        return('Você não tem acesso a essa área')
            
    if request.method == 'POST':
        evento.delete()
        return redirect('cal:calendar')
    
    return render(request, 'cal/delete.html', context)


def register(request):
    if request.user.is_authenticated:
        return redirect('cal:calendar')
    else:
        form = CreateFormUser()
        if request.method == 'POST':
            form = CreateFormUser(request.POST)
            if form.is_valid():
                form.save()

                user = form.cleaned_data.get('username')
                messages.success(request, 'A conta foi criada para ' + user)

                return redirect('cal:login')

    context = {'form': form}
    return render(request, "cal/register.html", context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('cal:calendar')
    else:
        if(request.method == 'POST'):

            user = authenticate(username=request.POST['username'], password=request.POST['password'])
            if user is not None:
                print('a')
                login(request, user)
                return redirect('cal:calendar')
            else:
                messages.info(request, "Usuário ou senha está incorreto.")

    context = {}       
    return render(request,'cal/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('cal:index')

def confirmation_event(request, pk):
    evento = Event.objects.get(id=pk)
    context = {'evento': evento}
    
    if request.method == 'POST':
        evento.pending = 1
        evento.save()
        return redirect('cal:calendar')

    return render(request, 'cal/confirm.html', context)

def deny_event(request, pk):
    evento = Event.objects.get(id=pk)
    form = ReasonForm()

    context = {'evento': evento, 'form':form}
    
    if request.method == 'POST':
        form = ReasonForm(request.POST)
        if(form.is_valid()):
            form.save()
        
        evento.reason = form.cleaned_data.get('reason')
        evento.pending = 2
        evento.save()
        return redirect('cal:calendar')

    return render(request, 'cal/deny.html', context)

cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
    integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Agendamento do Garagem</title>
</head>

<body>

  <h1 class="header">{% block header %}{% endblock %}</h1>
  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>

</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block header %}
{% if request.user.is_authenticated %}
<strong><a href="{%url 'cal:index' %}" >Agendamento do Garagem</a></strong>
{% if request.user.is_superuser %}
<span >Olá, ADM {{request.user}}</span>
{% else %}
<span >Olá, {{request.user}}</span>
{% endif %}
<span ><a href="{% url 'cal:logout' %}">Logout</a></span>
{% endif %}
{% endblock %}



{% block content %}
{% if request.user.is_authenticated %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Mês anterior </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Próximo mês </a>
	<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> Novo evento </a>
</div>

{{ calendar }}


{% else %}
<h1>Você não tem acesso a essa área!</h1>
<h2>Faça login para ver os agendamentos</h2>
<h2><a href="{% url 'cal:login' %}">Login</a></h2>
{% endif %}

{% endblock %}

cal/templates/cal/confirm.html
{% extends 'cal/base.html' %}

{% block title %}
Tem certeza que desejar confirmar "{{evento.title}}"?
{% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}

    <a class="btn btn-info left" href="{% url 'cal:event_info' evento.id %}?"> Voltar </a>
    <input type="submit" class="btn btn-info left" href="{% url 'cal:event_info' evento.id %}?" value="Confirmar"></input>

</form>
{% endblock content%}

cal/templates/cal/delete.html
{% extends 'cal/base.html' %}

{% block title %}
Tem certeza que desejar deletar "{{evento.title}}"?
{% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <a class="btn btn-info left" href="{% url 'cal:event_info' evento.id %}?"> Voltar </a>
    <input type="submit" class="btn btn-info left" href="{% url 'cal:event_info' evento.id %}?" value="Confirmar"></input>


</form>
{% endblock content%}

cal/templates/cal/deny.html
{% extends 'cal/base.html' %}

{% block title %}
Tem certeza que desejar negar "{{evento.title}}"?
{% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}

    {{form}}
    <a class="btn btn-info left" href="{% url 'cal:event_info' evento.id %}?"> Voltar </a>
    <input type="submit" class="btn btn-info left" href="{% url 'cal:event_info' evento.id %}?" value="Negar"></input>

</form>
{% endblock content%}

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendário </a>
</div>

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
  {{ field.label }} <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
  {{ field.label }} <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr>
      <td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td>
    </tr>
  </table>
</form>
{% endblock %}

cal/templates/cal/index.html
{% extends 'cal/base.html' %}

{%block title%}
<div class="CenterTitle">
<h1>Agendamento do Garagem {{evento.title}}</h1>
</div>
{%endblock%}

{% block content%}
<div class = "index">
<a class="btn btn-info" href="/register"> Cadastro de Usuário </a><br>
<a class="btn btn-info" href="/login"> Painel de Login </a><br>
<a class="btn btn-info" href="{% url 'cal:calendar' %}">Calendário</a><br>
</div>
{% endblock %}

cal/templates/cal/info.html
{% extends 'cal/base.html' %}

{% block title %}
Agendamento: {{evento.title}}
{% endblock %}

{% block content %}
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendário </a>
</div>

<div class="informacao">
    <h2><strong>Nome do agendamento: </strong>{{evento.title}}</h2>
    <h2><strong>Host: </strong>{{evento.host}}</h2>
    <h2><strong>Descrição: </strong>{{evento.description}}</h2>
    <h2><strong>Data e hora: </strong>{{evento.start_time}}</h2>
    {% if evento.pending == 0 %}
    <h2><strong>Condição: </strong> Pendente</h2>
    {% elif evento.pending == 1 %}
    <h2><strong>Situação: </strong> Confirmado por {{evento.adm}}</h2>
    {% elif evento.pending == 2 %}
    <h2><strong>Situação: </strong> Negado por {{evento.adm}}</h2>
    <h3><strong>Razão: </strong> {{evento.reason}}</h3>
    {% endif %}

</div>

{% if request.user == evento.host or request.user.is_superuser%}
{%if evento.pending == 0 or request.user.is_superuser%}
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:event_edit' evento.id%}"> Editar </a>
</div>
{%endif%}
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:event_delete' evento.id%}"> Deletar </a>
</div>
{% endif %}
{% if request.user.is_superuser and evento.pending == 0 %}
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:event_confirmation' evento.id%}"> Confirmar </a>
    <a class="btn btn-info left" href="{% url 'cal:event_denial' evento.id%}"> Negar </a>
</div>
{% endif %}
{% endblock content %}

cal/templates/cal/login.html
{% extends 'cal/base.html' %}

{% block title %}
<div class="CenterTitle">
<a href="{%url 'cal:index' %}" >Agendamento do Garagem</a>
</div>
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #FFFFFF !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: lightgrey;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: grey !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Não tem uma conta? <a href="{% url 'cal:register' %}" class="ml-2">Cadastre-se</a>
                    </div>
                    {% for message in messages %}
                    <p id="messages">{{message}}</p>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</body>

</html>
{% endblock %}

cal/templates/cal/register.html
{% extends 'cal/base.html' %}

{% block title %}
Agendamento:
{% endblock %}

{% block content%}

<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="Criar Usuário">
</form>
<p>Já tem uma conta? <a href="{% url 'cal:login'%}">Faça login</a></p>
{% endblock %}